### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by tashrifbillah** [reckbo/dtipipe#3]
It should fail given there is no `setup.py`

```
pip install git+https://github.com/reckbo/dtipipe.git
Collecting git+https://github.com/reckbo/dtipipe.git
  Cloning https://github.com/reckbo/dtipipe.git to /tmp/pip-req-build-hqhp622q
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/miniconda3/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-req-build-hqhp622q/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-req-build-hqhp622q/
```

**Comment by tashrifbillah** [comment]
Had to hack it as follows:

> cp -a dtipipe/src/dtipipe/ ~/miniconda3/lib/python3.6/site-packages/
